## 인구현황 데이터 전처리

In [1]:
import pandas as pd

In [3]:
# 세종시 연령별 인구현황 중 2020년 12월 데이터 불러오기
# 남/녀 구분 없이 다섯개 기준의 연령대 데이터로 전처리한 인구현황 데이터
f = pd.read_csv('./data/202012인구.csv')
f

        읍면동     전연령   0-19  20-39   40-69   70이상
0   세종특별자치시  354705  89942  98747  143470  22546
1      조치원읍   42789   7405  11834   18749   4801
2       연기면    2671    188    710    1341    432
3       연동면    3123    219    577    1548    779
4       부강면    6196    713   1463    2958   1062
5       금남면    8790    727   1765    4362   1936
6       장군면    6621    509   1837    3259   1016
7       연서면    7434    743   1600    3537   1554
8       전의면    5590    588   1074    2709   1219
9       전동면    3509    199    539    1890    881
10      소정면    2409    283    458    1187    481
11      한솔동   19208   5968   4309    8203    728
12      새롬동   29390   8161   9615   10843    771
13      도담동   39457  10925  11824   15182   1526
14      아름동   23525   7870   5217    9792    646
15      종촌동   29536   8894   8062   11406   1174
16      고운동   34387  10826   9258   13219   1084
17      소담동   32403   9154  10770   11655    824
18      보람동   19386   5701   5614    7456    615
19      대평동   10968   2704   3581    4324    359
20      다정동   27313   8165   8640    9850    658

In [4]:
f.iloc[0]

읍면동      세종특별자치시
전연령       354705
0-19       89942
20-39      98747
40-69     143470
70이상       22546
Name: 0, dtype: object

In [5]:
# 동별로 복제될 세종특별자치시 인구수 (5행)
new = pd.DataFrame(f.iloc[0][1:])
# index column 열 생성
new = new.reset_index()
# 열 이름 변경
new.columns = ['연령대', '세종시인구수']
# 연령대구분 열 생성
new['연령대구분'] = ['총거주자수', '아동청소년', '청년', '중장년', '노년']
new

     연령대  세종시인구수  연령대구분
0    전연령  354705  총거주자수
1   0-19   89942  아동청소년
2  20-39   98747     청년
3  40-69  143470    중장년
4   70이상   22546     노년

In [6]:
# 동 개수만큼 세종특별자치시 인구수 추가 (21 * 5 = 105)
new2 = new
for i in range(20):
    new = new.append(new2)
new

      연령대  세종시인구수  연령대구분
0     전연령  354705  총거주자수
1    0-19   89942  아동청소년
2   20-39   98747     청년
3   40-69  143470    중장년
4    70이상   22546     노년
..    ...     ...    ...
0     전연령  354705  총거주자수
1    0-19   89942  아동청소년
2   20-39   98747     청년
3   40-69  143470    중장년
4    70이상   22546     노년

[105 rows x 3 columns]

In [7]:
# 동 개수 list 생성
dong_list = f['읍면동'].unique()
dong_list

array(['세종특별자치시', '조치원읍', '연기면', '연동면', '부강면', '금남면', '장군면', '연서면', '전의면',
       '전동면', '소정면', '한솔동', '새롬동', '도담동', '아름동', '종촌동', '고운동', '소담동',
       '보람동', '대평동', '다정동'], dtype=object)

In [8]:
# 동 list도 데이터프레임 행 개수 (21*5=105) 로 만들어줌
new_dong_list = []
for i in dong_list:
    new_dong_list.append(i)
    new_dong_list.append(i)
    new_dong_list.append(i)
    new_dong_list.append(i)
    new_dong_list.append(i)
new_dong_list

['세종특별자치시',
 '세종특별자치시',
 '세종특별자치시',
 '세종특별자치시',
 '세종특별자치시',
 '조치원읍',
 '조치원읍',
 '조치원읍',
 '조치원읍',
 '조치원읍',
 '연기면',
 '연기면',
 '연기면',
 '연기면',
 '연기면',
 '연동면',
 '연동면',
 '연동면',
 '연동면',
 '연동면',
 '부강면',
 '부강면',
 '부강면',
 '부강면',
 '부강면',
 '금남면',
 '금남면',
 '금남면',
 '금남면',
 '금남면',
 '장군면',
 '장군면',
 '장군면',
 '장군면',
 '장군면',
 '연서면',
 '연서면',
 '연서면',
 '연서면',
 '연서면',
 '전의면',
 '전의면',
 '전의면',
 '전의면',
 '전의면',
 '전동면',
 '전동면',
 '전동면',
 '전동면',
 '전동면',
 '소정면',
 '소정면',
 '소정면',
 '소정면',
 '소정면',
 '한솔동',
 '한솔동',
 '한솔동',
 '한솔동',
 '한솔동',
 '새롬동',
 '새롬동',
 '새롬동',
 '새롬동',
 '새롬동',
 '도담동',
 '도담동',
 '도담동',
 '도담동',
 '도담동',
 '아름동',
 '아름동',
 '아름동',
 '아름동',
 '아름동',
 '종촌동',
 '종촌동',
 '종촌동',
 '종촌동',
 '종촌동',
 '고운동',
 '고운동',
 '고운동',
 '고운동',
 '고운동',
 '소담동',
 '소담동',
 '소담동',
 '소담동',
 '소담동',
 '보람동',
 '보람동',
 '보람동',
 '보람동',
 '보람동',
 '대평동',
 '대평동',
 '대평동',
 '대평동',
 '대평동',
 '다정동',
 '다정동',
 '다정동',
 '다정동',
 '다정동']

In [9]:
# 데이터프레임에 읍면동 열 추가 후 동 이름 할당
new['읍면동'] = new_dong_list
new

      연령대  세종시인구수  연령대구분      읍면동
0     전연령  354705  총거주자수  세종특별자치시
1    0-19   89942  아동청소년  세종특별자치시
2   20-39   98747     청년  세종특별자치시
3   40-69  143470    중장년  세종특별자치시
4    70이상   22546     노년  세종특별자치시
..    ...     ...    ...      ...
0     전연령  354705  총거주자수      다정동
1    0-19   89942  아동청소년      다정동
2   20-39   98747     청년      다정동
3   40-69  143470    중장년      다정동
4    70이상   22546     노년      다정동

[105 rows x 4 columns]

In [10]:
# 동 별 인구수 list 생성
population = []
for i in range(21):
    population.append(list(f.iloc[i][1:]))
population

[[354705, 89942, 98747, 143470, 22546],
 [42789, 7405, 11834, 18749, 4801],
 [2671, 188, 710, 1341, 432],
 [3123, 219, 577, 1548, 779],
 [6196, 713, 1463, 2958, 1062],
 [8790, 727, 1765, 4362, 1936],
 [6621, 509, 1837, 3259, 1016],
 [7434, 743, 1600, 3537, 1554],
 [5590, 588, 1074, 2709, 1219],
 [3509, 199, 539, 1890, 881],
 [2409, 283, 458, 1187, 481],
 [19208, 5968, 4309, 8203, 728],
 [29390, 8161, 9615, 10843, 771],
 [39457, 10925, 11824, 15182, 1526],
 [23525, 7870, 5217, 9792, 646],
 [29536, 8894, 8062, 11406, 1174],
 [34387, 10826, 9258, 13219, 1084],
 [32403, 9154, 10770, 11655, 824],
 [19386, 5701, 5614, 7456, 615],
 [10968, 2704, 3581, 4324, 359],
 [27313, 8165, 8640, 9850, 658]]

In [11]:
# 이제 인구수를 데이터프레임 개수만큼 할당하기 위해 인구수 2차원 list를 1차원 list로 변경 (5 * 21 = 105)
population2 = sum(population, [])
len(population2)

105

In [12]:
# 동별인구수 열 생성
new['동별인구수'] = population2
new

      연령대  세종시인구수  연령대구분      읍면동   동별인구수
0     전연령  354705  총거주자수  세종특별자치시  354705
1    0-19   89942  아동청소년  세종특별자치시   89942
2   20-39   98747     청년  세종특별자치시   98747
3   40-69  143470    중장년  세종특별자치시  143470
4    70이상   22546     노년  세종특별자치시   22546
..    ...     ...    ...      ...     ...
0     전연령  354705  총거주자수      다정동   27313
1    0-19   89942  아동청소년      다정동    8165
2   20-39   98747     청년      다정동    8640
3   40-69  143470    중장년      다정동    9850
4    70이상   22546     노년      다정동     658

[105 rows x 5 columns]

In [13]:
# 최종 데이터프레임 열 순서 변경
new = new[['읍면동', '동별인구수', '세종시인구수', '연령대', '연령대구분']]
new

        읍면동   동별인구수  세종시인구수    연령대  연령대구분
0   세종특별자치시  354705  354705    전연령  총거주자수
1   세종특별자치시   89942   89942   0-19  아동청소년
2   세종특별자치시   98747   98747  20-39     청년
3   세종특별자치시  143470  143470  40-69    중장년
4   세종특별자치시   22546   22546   70이상     노년
..      ...     ...     ...    ...    ...
0       다정동   27313  354705    전연령  총거주자수
1       다정동    8165   89942   0-19  아동청소년
2       다정동    8640   98747  20-39     청년
3       다정동    9850  143470  40-69    중장년
4       다정동     658   22546   70이상     노년

[105 rows x 5 columns]

In [14]:
# 전처리 완료한 인구 현황 데이터 저장
new.to_csv('./data/202012인구_전처리완료.csv', index = False, encoding = 'utf-8')